name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get repository name
        id: repo_name
        run: echo "repo_name=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.repo_name }}"
          path: |
            ./
            !.git/
            !.github/
            !.gitignore
