name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get repository name
        id: repo_name
        run: echo "repo_name=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Get version number from metadata.json
        id: version
        run: echo "version=$(jq -r .version metadata.json)" >> $GITHUB_ENV
        
      - name: Create build artifact
        run: |
          zip -r "${{ env.repo_name }}.zip" \
            $(git ls-files | grep -v -e '\.gitignore' -e '\.git/') \
            metadata.json

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "${{ env.repo_name }}-${{ env.version }}"
          path: "${{ env.repo_name }}.zip"
